<a href="https://colab.research.google.com/github/vitalinamysiv/restaurant-visitor-forecasting/blob/main/notebooks/00_prepare_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data preparation

## Goal

Prepare daily dataset for restaurant visitor forecasting.

The source dataset is Rossmann Store Sales.

The final dataset contains:

- date — observation date
- restaurant_id — store identifier
- guests — number of customers
- revenue — daily sales

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!git clone https://github.com/vitalinamysiv/restaurant-visitor-forecasting.git

Cloning into 'restaurant-visitor-forecasting'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 54 (delta 11), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (54/54), 15.99 KiB | 779.00 KiB/s, done.
Resolving deltas: 100% (11/11), done.

In [4]:
%cd restaurant-visitor-forecasting

/content/restaurant-visitor-forecasting

In [5]:
!ln -s /content/drive/MyDrive/restaurant_forecasting/data/raw/train.csv data/raw/train.csv

!ln -s /content/drive/MyDrive/restaurant_forecasting/data/raw/store.csv data/raw/store.csv

In [6]:
!python src/create_dataset.py

Загрузка данных...
Размер исходных данных: (1017209, 5)
Готово!
Размер обработанных данных: (844392, 4)
Сохранено: data/processed/restaurant_daily.csv

In [7]:
import pandas as pd

df_daily = pd.read_csv(
    "data/processed/restaurant_daily.csv",
    parse_dates=["date"]
)

df_daily.head()

   restaurant_id       date  revenue  guests
0              1 2013-01-02     5530     668
1              1 2013-01-03     4327     578
2              1 2013-01-04     4486     619
3              1 2013-01-05     4997     635
4              1 2013-01-07     7176     785

In [8]:
df_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 844392 entries, 0 to 844391
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   restaurant_id  844392 non-null  int64
 1   date           844392 non-null  datetime64[ns]
 2   revenue        844392 non-null  int64
 3   guests         844392 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 25.8 MB

In [9]:
df_daily.describe()

,restaurant_id,date,revenue,guests
count,844392.000000,844392,844392.000000,844392.000000
mean,558.422920,2014-04-11 01:02:42.487565312,6955.514291,762.728395
min,1.000000,2013-01-01 00:00:00,0.000000,0.000000
25%,280.000000,2013-08-16 00:00:00,4859.000000,519.000000
50%,558.000000,2014-03-31 00:00:00,6369.000000,676.000000
75%,837.000000,2014-12-10 00:00:00,8360.000000,893.000000
max,1115.000000,2015-07-31 00:00:00,41551.000000,7388.000000
std,321.731914,NaN,3104.214680,401.227674

In [10]:
print(
    "Начало:",
    df_daily["date"].min()
)

print(
    "Конец:",
    df_daily["date"].max()
)

Начало: 2013-01-01 00:00:00
Конец: 2015-07-31 00:00:00